title: "DESIGUALDADE DE GÊNERO E ETNIA NA ÁREA DE TECNOLOGIA"
description: "Mercado de trabalho americano.
Integrantes:

- Igor Henrique
- Jessica Sena
- Ricardo Barbosa"
show_downloads: false
google_analytics:
github:
  is_project_page: false
theme: jekyll-theme-cayman